language: csharp

os: osx
mono: latest

solution: XSVim.sln

before_install:
    - rvm get head

install:
    - nuget restore XSVim.sln
    - nuget install NUnit.Runners
    - wget https://dl.xamarin.com/VsMac/VisualStudioForMac-7.0.1.24.dmg
    - sudo hdiutil attach VisualStudioForMac-7.0.1.24.dmg

script:
  - xbuild
  - mono64 "/Volumes/Visual Studio/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/vstool.exe" run-md-tests XSVim.Tests/bin/Debug/XSVim.Tests.dll -labels
