language: csharp

os: osx
mono: latest

solution: XSVim.sln

before_install:
    - rvm get head

install:
    - nuget restore XSVim.sln
    - wget https://dl.xamarin.com/VsMac/VisualStudioForMac-7.0.1.24.dmg
    - sudo hdiutil attach VisualStudioForMac-7.0.1.24.dmg

script:
  - msbuild
  - mono64 "/Volumes/Visual Studio/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/vstool.exe" run-md-tests XSVim.Tests/bin/Debug/XSVim.Tests.dll -labels
  - mono64 "/Volumes/Visual Studio/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/vstool.exe" setup pack XSVim/bin/Debug/XSVim.dll 

deploy:
  provider: releases
  api_key: "f8c67a46952f852ba95af8207949d8f59cf04b44"
  file_glob: true
  file: XSVim/bin/Debug/*
  skip_cleanup: true
  on:
    tags: true
